name: Deploy to AWS EC2 with PM2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Install PM2
        run: npm install pm2 -g

      - name: Deploy application to EC2
        uses: appleboy/ssh-action@master
        with:
          host: i-059e5d4b855c6df24
          username: ec2-user
          key: MIIEogIBAAKCAQEAiuxVtBRRYIED804JnPySuTpUshkFSGSisODDt1EW3K3SOfbY
                dHRFs8cH5tfQjVgBJtgsci/glELzZsI57OD/Fgbk5w2JQuX95xYa4oXVNymN7Hto
                nMAFLhkbSWS+0ST1mWR9Gt6DmhcgA2Ib7R56Q8dNyyyyjw89efZprRTyT27+M0Aa
                nTk9A17j6whotTUQw/V7uuVHYE3FGqp7X66ItIFr5HBiODLvXFD+yp+SF8abf9ZM
                Yvzw8Hpw1R99zL6EznW5498azpbkePefYLXrECorM6gUU9RJRLLreBbfb3JzrVVW
                jIqL4cOALD5D5GT/iJyDXR3MN/Kia3U4shvqbwIDAQABAoIBAA8XMwwXtOtFuHci
                f/rUmN+UDYU3IJLHk8Cg+cGdBl28Z/yx6rtjsfqgYSRbRyVDbQSaMOHKf5u7VhNQ
                f9hSbIMpBo5usv1YXGdQyGTY4ttWITuSAEAev7FNOuCTGANB/4fFGa3kg+kmH+0e
                KChuyhs4uCOc3Fyb7DKmaL5LazLjkxKeyrAuLMbfCoY5i1hf89ccox6KWljFATuF
                uRTYQyNLckIKFOCqDRnK/Sk5GeD75CjNKzidqSrM5ng3aj+6QGjRNLG91LU8eUhJ
                PP2ZS3sJdi45sN0fpUoHr2I7Wc7FcvPt3i8X4jJVpKcSkb4qTSCyE39a9+JqvgWf
                ELynsFkCgYEA4Iy3W+tLY6Y1J1LAx9mhz6ZawyVLfhRNjZGeCiJvJTIVtjjtkgvm
                PwP2Z+P+hvR+13JO1LVrTsciO6y72q/QMx6VWZK2bgdFqWyNu6mzU30LZw8o/ifk
                NMK5wlJjrFkA9Cd/wdzvqsA77SWn0b8IE5LwarczoqFnaD6CPxv+/fUCgYEAnmF1
                rMm0IngajBxuQ9Typhbc1+Y00HwH6Y4MdOMC54jxyPaMKnEqbWSc8ACeai1ktWRl
                oNL4vSalJw6lWwIDyEft/Jn+w+YFTNt9OeGTnciqtxB4pYPp87lH5gNCf8lDg9xA
                vOQIS6xE+gaUZx2hRXbn0a7shvZtSut/o1QAxFMCgYB/ldSVCLM0MnrfFfjtVK3I
                41eMq8MiJv0NpCBs17XZJ4UInX32zoYLZf/6daPoIEF1vsAlwdLv1tuPlozCK8Ub
                VpQ7ac335G/jXQeHClwW4uS4sPd0uUvD4qRTUibKBWQyVcMUbqlKlqE2FIAu/+Dh
                5kpuCBvxms27gFDW9NxEhQKBgEBu2dbPwE79mZ9CucEy0vyq9HGJIBdpPjbQKVUs
                PbRATE07sE5b96zFb+tb9RaxHPWGwKmq6rLZE/tNxAvASBWk3bcUV0cPPzzDVrDD
                irB4QKt1Mf/0KKuUxyFWVilykdsFMfkmtBFFJlKpdpp0vXVrKGhvx54ohtIh+K1T
                sXQtAoGAcnO5UuJ4td/mtUWeg8fC+kd74X2+f9ngIJwbCvB4aTT0HhCtGPviJuJ2
                D6T4OA00c+gkGz/tsCoFcgnGi7nIGqfgfS0C3kFtwko8WFV8pNJUzgzu4Ry/5waC
                y/AiuPIQE0sWQO7EOAMcaYEc1fHmLA8btD7Y8R5lZQZc7p8m9FM=

          script: |
            cd /nodejs
            git pull origin main
            pm2 reload pm2.config.json --env production
